{"level":"info","ts":"2025-09-16T18:19:34.776+0500","caller":"logger/adapter.go:53","msg":"application starting","service":"order-service","env":"dev","env":"dev"}
{"level":"info","ts":"2025-09-16T18:19:34.780+0500","caller":"logger/adapter.go:53","msg":"starting metrics server","service":"order-service","env":"dev","port":"9090"}
{"level":"info","ts":"2025-09-16T18:19:34.793+0500","caller":"logger/adapter.go:100","msg":"starting cache restoration from database","service":"order-service","env":"dev","component":"order service"}
{"level":"error","ts":"2025-09-16T18:19:37.134+0500","caller":"logger/adapter.go:61","msg":"failed to restore cache from database","service":"order-service","env":"dev","error":"service.RestoreCache: get all order uids: repository.order.GetAllOrderUIDs: query: failed to connect to `user=admin database=orders_db`: hostname resolving error: lookup db: no such host","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nwbtest/internal/app.Run\n\tC:/Users/esandalov/Desktop/221/wb/l1/internal/app/app.go:63\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:33\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"info","ts":"2025-09-16T18:19:37.185+0500","caller":"logger/adapter.go:37","msg":"Starting HTTP Server goroutine...","service":"order-service","env":"dev"}
{"level":"info","ts":"2025-09-16T18:19:37.185+0500","caller":"logger/adapter.go:53","msg":"starting HTTP server","service":"order-service","env":"dev","component":"http server","addr":"0.0.0.0:8080"}
{"level":"info","ts":"2025-09-16T18:19:37.185+0500","caller":"logger/adapter.go:100","msg":"kafka reader info","service":"order-service","env":"dev","component":"kafka reader","message":"entering loop for consumer group, order-group-prod\n"}
{"level":"error","ts":"2025-09-16T18:19:39.574+0500","caller":"logger/adapter.go:61","msg":"application failed","service":"order-service","env":"dev","error":"app.initKafkaComponents: kafka reader creation: kafka.checkKafkaConnection: connect to kafka1:9092: failed to dial: failed to open connection to kafka1:9092: dial tcp: lookup kafka1: no such host","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:35\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"info","ts":"2025-09-16T18:19:39.574+0500","caller":"logger/adapter.go:53","msg":"application exited normally","service":"order-service","env":"dev"}
